-- AlterTable
ALTER TABLE "User" ADD COLUMN     "createdAccountAt" TIMESTAMP(3),
ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "isActive" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "joinedServerAt" TIMESTAMP(3),
ADD COLUMN     "lastSyncAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "premiumSince" TIMESTAMP(3);
